server:
  port: 8080
  servlet:
    context-path: /ecd
  tomcat:
    threads:
      max: 400
      min-spare: 20
    accept-count: 200
    connection-timeout: 30s
    keep-alive-timeout: 30s
    max-connections: 200
    max-http-form-post-size: 2048MB

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  application:
    name: ECD
    version: 2.0.1

  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    cors:
      allowed-origins:
        - http://localhost:8080
      allowed-methods: [ GET, POST, PUT, DELETE, OPTIONS ]
      allowed-headers: [ Authorization, Content-Type, X-Requested-With ]
      allow-credentials: true
    async:
      request-timeout: 300s

  datasource:
    url: jdbc:postgresql://db:5432/ecd
    username: postgres
    password: 2121
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: EcdHikariPool

      maximum-pool-size: 40
      minimum-idle: 10

      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

      auto-commit: false

      # ???????? ??? ???????????? ????
      validation-timeout: 5000



jwt:
  access:
    cookieName:
    expirationMs: 60000
  cookieName: geous-jwt
  jwtRefreshCookieName: geous-jwt-refresh
  jwtExpirationMs: 120000             # 2 ?????? = 120000 ??
  jwtRefreshExpirationMs: 2592000000  # 1 ?????
  access-token-secret: ebduebfyefvrewufvrerebcervrevrevbervbervbefvebhfvievbhevevev
  refresh-token-secret: iweucbewuibcvewicpwcneciwevrebvoreuviebvueirbviuevevoerveverovbreo
  refresh-token-expiration-days: 30
  access-token-expiration-minutes: 60
  issuer: "GEOUS"


